/*
	PUBLIC DATASET DOWNLOAD: https://www.kaggle.com/datasets/dhruvildave/spotify-charts
*/


SELECT DISTINCT
date_song,
--------- DATE ADD 
DATE_ADD(date_song, INTERVAL 1 DAY) AS ADD_1_DAY,
DATE_ADD(date_song, INTERVAL 5 DAY) AS ADD_5_DAY,
DATE_ADD(date_song, INTERVAL 3 MONTH) AS ADD_3_MONTH,
DATE_ADD(date_song, INTERVAL 5 MONTH) AS ADD_5_MONTH,
DATE_ADD(date_song, INTERVAL 2 YEAR) AS ADD_2_YEAR,
--------- DATE SUB
DATE_SUB(date_song, INTERVAL 1 DAY) AS SUB_1_DAY,
DATE_SUB(date_song, INTERVAL 5 DAY) AS SUB_5_DAY,
DATE_SUB(date_song, INTERVAL 3 MONTH) AS SUB_3_MONTH,
DATE_SUB(date_song, INTERVAL 2 YEAR) AS SUB_2_YEAR,
--------- DATE DIFF
DATE_DIFF('2017-01-02', '2017-01-06', DAY) AS DIFF_DAY,
DATE_DIFF('2017-04-04', '2017-06-04', MONTH) AS DIFF_MONTH,
DATE_DIFF('2017-02-04', '2019-02-04', YEAR) AS DIFF_YEAR

FROM `studies-377005.raw.spotify` 

ORDER BY date_song ASC 

LIMIT 1000

